#### Naive Bayes

Naive Bayes is a family of probabilistic classifiers based on Bayes' Theorem, with the "naive" assumption that all features are conditionally independent given the class label OR it predicts an outcome by calculating the probability of an event based on prior knowledge of conditions related to the event. It assumes that the features used to predict the target variable are independent to each other.

- Bayes' Theorem:
    P(y|X) = P(X|y) . P(y) / P(X)

- Where:
    - P(y∣X) - Posterior: probability of class y given features X
    - P(X∣y) - Likelihood: probability of features given class y
    - P(y) - Prior: overall probability of class y
    - P(X) - Evidence: constant, ignored during classification

- The Naive Assumption:
    - Naive Bayes assumes all features are independent given the class, so:
        - P(X∣C)= P(x1​,x2​,...,xn​∣C) = P(x1​∣C) ⋅ P(x2​∣C) ⋅ ... ⋅P(xn​∣C)

- Assumptions:
    - Simple but powerful algorithm for predictive modeling
    - Based on Bayes' Theorem
    - Useful in text classification tasks such as spam filtering, and sentiment analysis

- Types:
    - Gaussian NB:
        - Used when features are continuous and normally distributed

    - Multinomial NB:
        - Often used for document classification, where the features are the frequencies of the words or tokens in the documents

    - Bernoulli NB:
        - Used when features are binary (0s r 1s)


- Applications:
    - Email Spam Filtering
    - Sentiment Analysis
    - Document Categorization
    - Medical Diagnosis

- Advantages
    - Simplicity: Straightforward to imlement and understand
    - Efficiency - Requires a small amount of training data to estimate the necessary parameters
    - Speed - Vert fast, making them suitable for real-time predictions
    - Good Performance: Often performs well in multi class prediction

- An example: https://www.youtube.com/watch?v=WghrAfcdUg8&list=PL9XvIvvVL50FfLhE7yjg5UXBmeoppX0dI&index=71

- Concrete Example:
    - Training data: 10 emails total
        - 6 are spam,  4 are ham (not spam)
        - "free" appears in 5 of 6 spam emails
        - "free" appears in 1 of 4 ham  emails

- New email contains the word "free". Spam or ham?

- For SPAM:
  - P(spam) × P("free" | spam)
  - = 0.6 × (5/6)
  - = 0.6 × 0.83
  - = 0.50

- For HAM:
  - P(ham) × P("free" | ham)
  - = 0.4 × (1/4)
  - = 0.4 × 0.25
  - = 0.10

Result: 0.50 > 0.10  →  Predicted: SPAM

- We don't even need the bottom part of the fraction P(X) because it's the same for both — it cancels out.

#### Another Example

- Naive Bayes Example: Titanic Dataset (2 Features)

    - We want to predict Survived (Yes or No) using two features: Sex and Class.

    - Step 0: Tiny dataset
        - Sex | Class | Survived
        - Male | 1st | Yes
        - Female | 1st | Yes
        - Male | 3rd | No
        - Female | 2nd | Yes
        - Male | 2nd | No
        - Female | 3rd | No

    - Step 1: Compute class priors

        - P(Yes) = 3 / 6 = 0.5
        - P(No) = 3 / 6 = 0.5

    - Step 2: Compute feature likelihoods

        - Feature 1: Sex
        - P(Male given Yes) = 1 / 3 = 0.33
        - P(Female given Yes) = 2 / 3 = 0.67
        - P(Male given No) = 2 / 3 = 0.67
        - P(Female given No) = 1 / 3 = 0.33

        - Feature 2: Class
        - P(1st given Yes) = 2 / 3 = 0.67
        - P(2nd given Yes) = 1 / 3 = 0.33
        - P(3rd given Yes) = 0 / 3 = 0
        - P(1st given No) = 0 / 3 = 0
        - P(2nd given No) = 1 / 3 = 0.33
        - P(3rd given No) = 2 / 3 = 0.67

    - Step 3: Predict a new passenger

        - New passenger: Female, 3rd class

        - Without smoothing:
        - Posterior Yes = 0.5 * 0.67 * 0 = 0
        - Posterior No = 0.5 * 0.33 * 0.67 = 0.11
        - Prediction: No

        - With Laplace smoothing:
        - P(3rd given Yes) = (0 + 1) / (3 + 3) = 1 / 6 = 0.17
        - Posterior Yes = 0.5 * 0.67 * 0.17 = 0.057
        - Posterior No = 0.5 * 0.33 * 0.67 = 0.11
        - Prediction: No (still)

    - Key takeaway: Multiply prior with all feature probabilities and pick the higher one.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = sns.load_dataset('iris')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [2]:
X = df.drop('species', axis=1)
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

gnb = GaussianNB()

gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

Accuracy:  1.0


In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris

df = load_iris()

X = df.data
y = df.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

print("accuracy_score: ", accuracy_score(y_test, y_pred))
print("classification_report:\n", classification_report(y_test, y_pred))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

accuracy_score:  1.0
classification_report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [8]:
# Multinomial NB

mnb = MultinomialNB()
mnb.fit(X_train, y_train)
y_pred = mnb.predict(X_test)

print("accuracy_score: ", accuracy_score(y_test, y_pred))
print("classification_report:\n", classification_report(y_test, y_pred))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

accuracy_score:  0.9
classification_report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30

confusion_matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]


In [9]:
import warnings
warnings.filterwarnings('ignore')

# Bernoulli NB
bnb = BernoulliNB()
bnb.fit(X_train, y_train)
y_pred = bnb.predict(X_test)

print("accuracy_score: ", accuracy_score(y_test, y_pred))
print("classification_report:\n", classification_report(y_test, y_pred))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

accuracy_score:  0.3
classification_report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30

confusion_matrix:
 [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]


In [6]:
# Our data distribution is normal that's why GaussianNB worked well.

- Bernoulli assumes that features are binary

Features are all **binary (yes/no → 1/0):**

| Student | Attended Class | Did Homework | Studied Night Before | **Pass?** |
|---------|---------------|--------------|----------------------|-----------|
| 1 | 1 | 1 | 1 | Yes |
| 2 | 1 | 1 | 0 | Yes |
| 3 | 1 | 0 | 1 | Yes |
| 4 | 0 | 1 | 0 | No |
| 5 | 0 | 0 | 1 | No |
| 6 | 1 | 0 | 0 | No |
| 7 | 0 | 0 | 0 | No |
| 8 | 1 | 1 | 1 | Yes |